import { getCookie } from 'hono/cookie';
import { Hono, type Context } from 'hono';
import { prisma } from '../../lib/prisma.js';
import { getCurrentUser } from '../auth/auth.service.js';
import { z } from 'zod';
async function currentUser(c: Context) { try { return await getCurrentUser(getCookie(c, 'workpilot_access') ?? ''); } catch { return null; } }
const siteSchema = z.object({ name: z.string().trim().min(2).max(100), location: z.string().trim().min(2).max(200), isActive: z.boolean().default(true) });
const shiftSchema = z.object({ name: z.string().trim().min(2).max(100), startTime: z.string().regex(/^\d{2}:\d{2}$/), endTime: z.string().regex(/^\d{2}:\d{2}$/), isActive: z.boolean().default(true) });
async function reviewer(c: Context) { const user = await currentUser(c); return user && ['hr', 'admin'].includes(user.role) ? user : null; }
export const hrSettingsRoutes = new Hono()
  .get('/sites', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); return c.json({ sites: await prisma.site.findMany({ orderBy: { name: 'asc' } }) }); })
  .post('/sites', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const data = siteSchema.safeParse(await c.req.json().catch(() => null)); if (!data.success) return c.json({ message: 'Invalid site information.' }, 400); const site = await prisma.site.create({ data: data.data }).catch(() => null); return site ? c.json({ site }, 201) : c.json({ message: 'A site with this name already exists.' }, 409); })
  .patch('/sites/:id', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const data = siteSchema.safeParse(await c.req.json().catch(() => null)); if (!data.success) return c.json({ message: 'Invalid site information.' }, 400); const site = await prisma.site.update({ where: { id: c.req.param('id') }, data: data.data }).catch(() => null); return site ? c.json({ site }) : c.json({ message: 'Site not found.' }, 404); })
  .delete('/sites/:id', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const site = await prisma.site.delete({ where: { id: c.req.param('id') } }).catch(() => null); return site ? c.json({ message: 'Site deleted.' }) : c.json({ message: 'Site cannot be deleted because it is used by attendance records.' }, 409); })
  .get('/shifts', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); return c.json({ shifts: await prisma.shift.findMany({ orderBy: { startTime: 'asc' } }) }); })
  .post('/shifts', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const data = shiftSchema.safeParse(await c.req.json().catch(() => null)); if (!data.success) return c.json({ message: 'Invalid shift information.' }, 400); const shift = await prisma.shift.create({ data: data.data }).catch(() => null); return shift ? c.json({ shift }, 201) : c.json({ message: 'A shift with this name already exists.' }, 409); })
  .patch('/shifts/:id', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const data = shiftSchema.safeParse(await c.req.json().catch(() => null)); if (!data.success) return c.json({ message: 'Invalid shift information.' }, 400); const shift = await prisma.shift.update({ where: { id: c.req.param('id') }, data: data.data }).catch(() => null); return shift ? c.json({ shift }) : c.json({ message: 'Shift not found.' }, 404); })
  .delete('/shifts/:id', async (c) => { if (!await reviewer(c)) return c.json({ message: 'Unauthorized.' }, 403); const shift = await prisma.shift.delete({ where: { id: c.req.param('id') } }).catch(() => null); return shift ? c.json({ message: 'Shift deleted.' }) : c.json({ message: 'Shift cannot be deleted because it is used by attendance records.' }, 409); });
